apiVersion: networking.k8s.io/v1 
kind: Ingress 
metadata: 
  name: ingress
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9113"
    prometheus.io/scheme: http
spec: 
  ingressClassName: nginx 
  rules: 
  - host: peerchat.test 
    http: 
      paths: 
        - backend: 
            service: 
              name: frontend
              port: 
                number: 3000
          path: /(.*)
          pathType: Prefix 