apiVersion: keda.sh/v1alpha1 
kind: ScaledObject 
metadata: 
  name: nginx-scale 
spec: 
  scaleTargetRef: 
    kind: Deployment 
    name: main-nginx-ingress 
  minReplicaCount: 1 
  maxReplicaCount: 20 
  cooldownPeriod: 30 
  pollingInterval: 1 
  triggers: 
  - type: prometheus 
    metadata: 
      serverAddress: http://prometheus-server 
      metricName: nginx_connections_active_keda 
      query: sum(avg_over_time(nginx_ingress_nginx_connections_active{app="main-nginx-ingress"}[1m])) 
      threshold: "100" 
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata: 
  name: frontend-scale 
spec:
  scaleTargetRef: 
    kind: Deployment 
    name: frontend
  minReplicaCount: 1
  maxReplicaCount: 30
  pollingInterval: 5
  cooldownPeriod:  5
  triggers:
    - type: prometheus
      metadata: 
        serverAddress: http://prometheus-server 
        metricName: nodejs_http_request_duration_seconds_bucket
        query: rate(nodejs_http_request_duration_seconds_bucket{le="5"}[10m])
        threshold: "200"
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata: 
  name: users-scale 
spec:
  scaleTargetRef: 
    kind: Deployment 
    name: user-service
  minReplicaCount: 1
  maxReplicaCount: 30
  pollingInterval: 5
  cooldownPeriod:  5
  triggers:
    - type: prometheus
      metadata: 
        serverAddress: http://prometheus-server 
        metricName: api_http_requests_duration_seconds_bucket
        query: rate(api_http_requests_duration_seconds_bucket{service="user-service",le="10"}[10m])
        threshold: "200"
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata: 
  name: messages-scale 
spec:
  scaleTargetRef: 
    kind: Deployment 
    name: message-relay
  minReplicaCount: 1
  maxReplicaCount: 30
  pollingInterval: 5
  cooldownPeriod:  5
  triggers:
    - type: prometheus
      metadata: 
        serverAddress: http://prometheus-server 
        metricName: api_http_requests_duration_seconds_bucket
        query: rate(api_http_requests_duration_seconds_bucket{service="message-relay",le="10"}[10m])
        threshold: "200"