apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata: 
 name: nginx-scale 
spec:
  minReplicaCount: 1
  maxReplicaCount: 30
  pollingInterval: 5
  cooldownPeriod:  5
  scaleTargetRef: 
    kind: Deployment 
    name: main-nginx-ingress 
  triggers:
    - type: prometheus
      metadata: 
        serverAddress: http://192.168.49.2:30010
        metricName: nodejs_http_request_duration_seconds_bucket
        query: |
          nodejs_http_request_duration_seconds_bucket{app="frontend"}
          threshold: 1.5