on:
  push:
  workflow_dispatch:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2

    - 
      name: Build
      run: | 
        CI=false
        cd frontend
        npm install
        npm run build

  build-message-relay:
    runs-on: ubuntu-latest

    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2

    - 
      name: Build
      run: | 
        cd message-relay
        cargo build -r

  build-user-service:
    runs-on: ubuntu-latest

    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2

    - 
      name: Build
      run: | 
        cd user-service
        cargo build -r
        
  publish-to-dockerhub:
    needs: [build-frontend, build-message-relay, build-user-service]
    runs-on: ubuntu-latest
    
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: frontend-env
      run: |
        cd frontend/
        echo "REACT_APP_AUTH0_DOMAIN=${{ secrets.AUTH0_DOMAIN }}" >> .env
        echo "REACT_APP_AUTH0_CLIENTID=${{ secrets.AUTH0_CLIENTID }}" >> .env
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    -
      name: push-frontend
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        push: true
        tags: malpa222/peerchat:frontend
    - 
      name: push-message-relay
      uses: docker/build-push-action@v2
      with:
        context: ./message-relay
        push: true
        tags: malpa222/peerchat:message-relay
    - 
      name: push-user-service
      uses: docker/build-push-action@v2
      with:
        context: ./user-service
        push: true
        tags: malpa222/peerchat:user-service