name: CI
on:
  push:
    branches:
      - master
  workflow_dispatch:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-message-relay:
    runs-on: ubuntu-latest

    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2

    - 
      name: Build
      run: | 
        cd message-relay
        cargo build -r
        
  publish-to-dockerhub:
    needs: build-message-relay
    runs-on: ubuntu-latest
    
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - 
      name: push
      uses: docker/build-push-action@v2
      with:
        context: ./message-relay
        push: true
        tags: malpa222/peerchat:message-relay
    
