name: CI

on:
  push:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-client:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Prepare env
      run: |
        cd chat-client
        sudo apt update && sudo apt install -y libwebkit2gtk-4.0-dev \
          build-essential \
          curl \
          wget \
          libssl-dev \
          libgtk-3-dev \
          libappindicator3-dev \
          librsvg2-dev
        npm install
    
    - name: Build
      run: | 
        CI=false
        cd chat-client
        npm run tauri build

  build-message-relay:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: | 
        cd message-relay
        cargo build -r