on:
  push:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2

    - 
      name: Build
      run: | 
        CI=false
        cd frontend
        npm install
        npm run build

  publish-frontend:
    needs: build-frontend
    runs-on: ubuntu-latest
  
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: frontend-env
      run: |
        cd frontend/
        echo "REACT_APP_AUTH0_DOMAIN=${{ secrets.AUTH0_DOMAIN }}" >> .env
        echo "REACT_APP_AUTH0_CLIENTID=${{ secrets.AUTH0_CLIENTID }}" >> .env
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    -
      name: push-frontend
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        push: true
        tags: malpa222/peerchat:frontend

  build-message-relay:
    runs-on: ubuntu-latest

    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2

    - 
      name: Build
      run: | 
        cd message-relay
        cargo build -r

  build-user-service:
    runs-on: ubuntu-latest

    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2

    - 
      name: Build
      run: | 
        cd user-service
        cargo build -r
  
  publish-user-service:
    needs: build-user-service
    runs-on: ubuntu-latest
  
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: users-env
      run: |
        cd frontend/
        echo "AUTH0_DOMAIN=${{ secrets.AUTH0_DOMAIN }}" >> .env
        echo "AUTH0_CLIENTID=${{ secrets.AUTH0_CLIENTID }}" >> .env
        echo "AUTH0_CLIENT_SECRET=${{ secrets.USERS_AUTH0_SECRET }}" >> .env
        echo "SERVER_ADDR=0.0.0.0" >> .env
        echo "SERVER_PORT=8080" >> .env
        echo "DATABASE_URL=${{ secrets.DB_URL }}" >> .env
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    -
      name: push-frontend
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        push: true
        tags: malpa222/peerchat:frontend