on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  publish-frontend:
    runs-on: ubuntu-latest
    
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    -
      name: push-frontend
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        push: true
        tags: malpa222/peerchat:frontend

  publish-message-relay:
    runs-on: ubuntu-latest
    
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - 
      name: push-message-relay
      uses: docker/build-push-action@v2
      with:
        context: ./message-relay
        push: true
        tags: malpa222/peerchat:message-relay

  publish-user-service:
    runs-on: ubuntu-latest
    
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - 
      name: push-user-service
      uses: docker/build-push-action@v2
      with:
        context: ./user-service
        push: true
        tags: malpa222/peerchat:user-service